/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83GjuDZ4D61E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83GjuDZ4D61E= >>
// ----------- >>
public class Cita {
    // ----------- << attribute.annotations@AAAAAAF83HjHr58oBg8= >>
    // ----------- >>
    private int idCita;

    // ----------- << attribute.annotations@AAAAAAF83H1kF58vYv4= >>
    // ----------- >>
    private LocalDate fechaCita;

    // ----------- << attribute.annotations@AAAAAAF83H3JoZ827k8= >>
    // ----------- >>
    private Paciente paciente;

    // ----------- << attribute.annotations@AAAAAAF83H3YDp88+8I= >>
    // ----------- >>
    private Medico medico;

    // ----------- << attribute.annotations@AAAAAAF83LQspa6nUx8= >>
    // ----------- >>
    private Medico ;

    // ----------- << attribute.annotations@AAAAAAF83Lf3ZLzoyV4= >>
    // ----------- >>
    private Medico ;

    // ----------- << attribute.annotations@AAAAAAF83LUYVbF4Ods= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83Lfb9Lu+iTA= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83LtXx9VDgj4= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83Ly2KeJ8xHA= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83LhWUsDIw3k= >>
    // ----------- >>
    private Receta ;

    // ----------- << attribute.annotations@AAAAAAF83LdTNbgEK7I= >>
    // ----------- >>
    private Main ;

    private int getIdCita() {
        return idCita;
    }

    private LocalDate getFechaCita() {
        return fechaCita;
    }

    private Paciente getPaciente() {
        return paciente;
    }

    private Medico getMedico() {
        return medico;
    }

    public Medico get() {
        return ;
    }

    public Medico get() {
        return ;
    }

    public Paciente get() {
        return ;
    }

    public Paciente get() {
        return ;
    }

    public Paciente get() {
        return ;
    }

    public Paciente get() {
        return ;
    }

    public Receta get() {
        return ;
    }

    public Main get() {
        return ;
    }

    private void setIdCita(int idCita) {
        this.idCita = idCita;
    }

    private void setFechaCita(LocalDate fechaCita) {
        this.fechaCita = fechaCita;
    }

    private void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    private void setMedico(Medico medico) {
        this.medico = medico;
    }

    public void set(Medico ) {
        this. = ;
    }

    public void set(Medico ) {
        this. = ;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Receta ) {
        this. = ;
    }

    public void set(Main ) {
        this. = ;
    }

    public void link(Medico _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Medico _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Receta _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Main _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF83JepXaB0aWs= >>
    // ----------- >>
    public void altaCita() {
    // ----------- << method.body@AAAAAAF83JepXaB0aWs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JfJ6qB71sE= >>
    // ----------- >>
    public void bajaCita() {
    // ----------- << method.body@AAAAAAF83JfJ6qB71sE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JfMvqCBKbQ= >>
    // ----------- >>
    public void actualizaCita() {
    // ----------- << method.body@AAAAAAF83JfMvqCBKbQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JfYHqCHpZg= >>
    // ----------- >>
    public void consultaCita() {
    // ----------- << method.body@AAAAAAF83JfYHqCHpZg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83KsReqM8Ho4= >>
    // ----------- >>
    public void generarReceta() {
    // ----------- << method.body@AAAAAAF83KsReqM8Ho4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83GjuDZ4D61E= >>
// ----------- >>
}