/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83JQmw5/+VDI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83JQmw5/+VDI= >>
// ----------- >>
public class Main {
    // ----------- << attribute.annotations@AAAAAAF83J2aP6DRZlo= >>
    // ----------- >>
    private String usuario;

    // ----------- << attribute.annotations@AAAAAAF83J3GDqDYs6g= >>
    // ----------- >>
    private String contraseña;

    // ----------- << attribute.annotations@AAAAAAF83J43IqDgj04= >>
    // ----------- >>
    private boolean usuarioValido;

    // ----------- << attribute.annotations@AAAAAAF83LsCiNCxS8U= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83Lbj/rbn0LQ= >>
    // ----------- >>
    private Usuario ;

    // ----------- << attribute.annotations@AAAAAAF83LdTNbgFNTU= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83LxK0t93Kag= >>
    // ----------- >>
    private Medico ;

    private String getUsuario() {
        return usuario;
    }

    private String getContraseña() {
        return contraseña;
    }

    private boolean isUsuarioValido() {
        return usuarioValido;
    }

    public Paciente get() {
        return ;
    }

    public Usuario get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Medico get() {
        return ;
    }

    private void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    private void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

    private void setUsuarioValido(boolean usuarioValido) {
        this.usuarioValido = usuarioValido;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Usuario ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Medico ) {
        this. = ;
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Usuario _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Medico _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF83JudI6DBb7A= >>
    // ----------- >>
    public void validarCredenciales() {
    // ----------- << method.body@AAAAAAF83JudI6DBb7A= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JvrmqDI9PI= >>
    // ----------- >>
    public void menu() {
    // ----------- << method.body@AAAAAAF83JvrmqDI9PI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83JQmw5/+VDI= >>
// ----------- >>
}