/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83IyCGJ9yIh0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83IyCGJ9yIh0= >>
// ----------- >>
public class Medicamento {
    // ----------- << attribute.annotations@AAAAAAF83JVfiqBA8a0= >>
    // ----------- >>
    private String idMedicamento;

    // ----------- << attribute.annotations@AAAAAAF83JWOPqBHx0o= >>
    // ----------- >>
    private String descripcion;

    // ----------- << attribute.annotations@AAAAAAF83KkglaFewlE= >>
    // ----------- >>
    private Receta ;

    // ----------- << attribute.annotations@AAAAAAF83Knb16J7KVk= >>
    // ----------- >>
    private Receta ;

    // ----------- << attribute.annotations@AAAAAAF83K8H9KXZpZI= >>
    // ----------- >>
    private Receta *;

    // ----------- << attribute.annotations@AAAAAAF83LHktqqxsH8= >>
    // ----------- >>
    private Receta ;

    private String getIdMedicamento() {
        return idMedicamento;
    }

    private String getDescripcion() {
        return descripcion;
    }

    public Receta get() {
        return ;
    }

    public Receta get() {
        return ;
    }

    public Receta get*() {
        return *;
    }

    public Receta get() {
        return ;
    }

    private void setIdMedicamento(String idMedicamento) {
        this.idMedicamento = idMedicamento;
    }

    private void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public void set(Receta ) {
        this. = ;
    }

    public void set(Receta ) {
        this. = ;
    }

    public void set*(Receta *) {
        this.* = *;
    }

    public void set(Receta ) {
        this. = ;
    }

    public void link(Receta _) {
        set(_);
    }

    public void link(Receta _) {
        set(_);
    }

    public void link*(Receta _*) {
        if (_* != null) {
            _*.unlink1();
            _*.set1(this);
        }

        unlink*();
        set*(_*);
    }

    public void link(Receta _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        set(null);
    }

    public void unlink*() {
        if (get*() != null) {
            get*().set1(null);
            set*(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF83Jnz0qCqlxU= >>
    // ----------- >>
    public void altaMedicamento() {
    // ----------- << method.body@AAAAAAF83Jnz0qCqlxU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JrDSqC4aTc= >>
    // ----------- >>
    public void bajaMedicamento() {
    // ----------- << method.body@AAAAAAF83JrDSqC4aTc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JqGGqCxa8M= >>
    // ----------- >>
    public void consultarMedicamento() {
    // ----------- << method.body@AAAAAAF83JqGGqCxa8M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83IyCGJ9yIh0= >>
// ----------- >>
}