/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83GjCZ52vV74= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83GjCZ52vV74= >>
// ----------- >>
public class Medico extends Persona,Persona {
    // ----------- << attribute.annotations@AAAAAAF83HCC2J6Al1I= >>
    // ----------- >>
    private void idMedico;

    // ----------- << attribute.annotations@AAAAAAF83HCyNZ6HwCU= >>
    // ----------- >>
    private int NoCedula;

    // ----------- << attribute.annotations@AAAAAAF83HC/NZ6Ndjg= >>
    // ----------- >>
    private void Attribute2;

    // ----------- << attribute.annotations@AAAAAAF83HDJpZ6T7aU= >>
    // ----------- >>
    private void Attribute3;

    // ----------- << attribute.annotations@AAAAAAF83HMTEJ6vlo0= >>
    // ----------- >>
    private String especialidad;

    // ----------- << attribute.annotations@AAAAAAF83LO7Haz8cTw= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83LQspa6okko= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83Lf3ZLzp8Qc= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83Lkg9MSXT7Y= >>
    // ----------- >>
    private Paciente ;

    // ----------- << attribute.annotations@AAAAAAF83LxK0t926s0= >>
    // ----------- >>
    private Main ;

    private void getIdMedico() {
        return idMedico;
    }

    private int getNoCedula() {
        return NoCedula;
    }

    public void getAttribute2() {
        return Attribute2;
    }

    public void getAttribute3() {
        return Attribute3;
    }

    private String getEspecialidad() {
        return especialidad;
    }

    public Paciente get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Paciente get() {
        return ;
    }

    public Main get() {
        return ;
    }

    private void setIdMedico(void idMedico) {
        this.idMedico = idMedico;
    }

    private void setNoCedula(int NoCedula) {
        this.NoCedula = NoCedula;
    }

    public void setAttribute2(void Attribute2) {
        this.Attribute2 = Attribute2;
    }

    public void setAttribute3(void Attribute3) {
        this.Attribute3 = Attribute3;
    }

    private void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Paciente ) {
        this. = ;
    }

    public void set(Main ) {
        this. = ;
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Paciente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Main _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF83JYQfKBPpyc= >>
    // ----------- >>
    public void AltaMedico() {
    // ----------- << method.body@AAAAAAF83JYQfKBPpyc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JY116BWndk= >>
    // ----------- >>
    public void BajaMedico() {
    // ----------- << method.body@AAAAAAF83JY116BWndk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JZWlaBd5A8= >>
    // ----------- >>
    public void consultaMedico() {
    // ----------- << method.body@AAAAAAF83JZWlaBd5A8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83GjCZ52vV74= >>
// ----------- >>
}