/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83GjW1J3ZXLc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83GjW1J3ZXLc= >>
// ----------- >>
public class Paciente extends Persona,Persona,Persona {
    // ----------- << attribute.annotations@AAAAAAF83HHPsJ6mFgs= >>
    // ----------- >>
    private void idPaciente;

    // ----------- << attribute.annotations@AAAAAAF83LO7Haz7b+Y= >>
    // ----------- >>
    private Medico ;

    // ----------- << attribute.annotations@AAAAAAF83Lkg9MSWLcE= >>
    // ----------- >>
    private Medico ;

    // ----------- << attribute.annotations@AAAAAAF83LUYVbF50lg= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83Lfb9Lu/6dM= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83LsCiNCyazA= >>
    // ----------- >>
    private Main ;

    // ----------- << attribute.annotations@AAAAAAF83LtXx9VECT0= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83Ly2KeJ9bg4= >>
    // ----------- >>
    private Cita ;

    private void getIdPaciente() {
        return idPaciente;
    }

    public Medico get() {
        return ;
    }

    public Medico get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Main get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    private void setIdPaciente(void idPaciente) {
        this.idPaciente = idPaciente;
    }

    public void set(Medico ) {
        this. = ;
    }

    public void set(Medico ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Main ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void link(Medico _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Medico _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Main _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF83HG0wJ6f7AY= >>
    // ----------- >>
    public void altaPaciente() {
    // ----------- << method.body@AAAAAAF83HG0wJ6f7AY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JbwxaBlVMc= >>
    // ----------- >>
    public void actualizaPaciente() {
    // ----------- << method.body@AAAAAAF83JbwxaBlVMc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83JdgWqBsIvc= >>
    // ----------- >>
    public void consultaPaciente() {
    // ----------- << method.body@AAAAAAF83JdgWqBsIvc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83GjW1J3ZXLc= >>
// ----------- >>
}