/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83GiKZJ2FBU0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83GiKZJ2FBU0= >>
// ----------- >>
public class Persona {
    // ----------- << attribute.annotations@AAAAAAF83GuxBJ4z3I4= >>
    // ----------- >>
    private int idPersona;

    // ----------- << attribute.annotations@AAAAAAF83GxLuJ47XVQ= >>
    // ----------- >>
    private String nombre;

    // ----------- << attribute.annotations@AAAAAAF83GyGCJ5CPR0= >>
    // ----------- >>
    private String apPaterno;

    // ----------- << attribute.annotations@AAAAAAF83GyL2J5I+Bw= >>
    // ----------- >>
    private String apMaterno;

    // ----------- << attribute.annotations@AAAAAAF83GyO0J5OJrU= >>
    // ----------- >>
    private LocalDate fechaNacimiento;

    // ----------- << attribute.annotations@AAAAAAF83G2GeJ5XWXs= >>
    // ----------- >>
    private void edad;

    // ----------- << attribute.annotations@AAAAAAF83G2bCJ5dLDU= >>
    // ----------- >>
    private void sexo;

    // ----------- << attribute.annotations@AAAAAAF83G3ugJ5l7Ks= >>
    // ----------- >>
    private void direccion;

    // ----------- << attribute.annotations@AAAAAAF83HQNH564PFk= >>
    // ----------- >>
    private int telefono;

    private int getIdPersona() {
        return idPersona;
    }

    private String getNombre() {
        return nombre;
    }

    private String getApPaterno() {
        return apPaterno;
    }

    private String getApMaterno() {
        return apMaterno;
    }

    private LocalDate getFechaNacimiento() {
        return fechaNacimiento;
    }

    private void getEdad() {
        return edad;
    }

    private void getSexo() {
        return sexo;
    }

    private void getDireccion() {
        return direccion;
    }

    private int getTelefono() {
        return telefono;
    }

    private void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    private void setNombre(String nombre) {
        this.nombre = nombre;
    }

    private void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }

    private void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }

    private void setFechaNacimiento(LocalDate fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    private void setEdad(void edad) {
        this.edad = edad;
    }

    private void setSexo(void sexo) {
        this.sexo = sexo;
    }

    private void setDireccion(void direccion) {
        this.direccion = direccion;
    }

    private void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    // ----------- << method.annotations@AAAAAAF83G+RqJ50bWs= >>
    // ----------- >>
    public void Operation1() {
    // ----------- << method.body@AAAAAAF83G+RqJ50bWs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83GiKZJ2FBU0= >>
// ----------- >>
}