/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83IwL0J9IV4s= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83IwL0J9IV4s= >>
// ----------- >>
public class Receta {
    // ----------- << attribute.annotations@AAAAAAF83JSNbaApYR4= >>
    // ----------- >>
    private int idReceta;

    // ----------- << attribute.annotations@AAAAAAF83JSy76Aw0rA= >>
    // ----------- >>
    private String dosis;

    // ----------- << attribute.annotations@AAAAAAF83JTqoKA33ig= >>
    // ----------- >>
    private void idMedicamento;

    // ----------- << attribute.annotations@AAAAAAF83KthZaN+BvQ= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83LhWUsDJUXw= >>
    // ----------- >>
    private Cita ;

    // ----------- << attribute.annotations@AAAAAAF83K8H9KXYmY4= >>
    // ----------- >>
    private Medicamento 1;

    // ----------- << attribute.annotations@AAAAAAF83LHktqqwa6k= >>
    // ----------- >>
    private Set<Medicamento>  = new HashSet<>();

    private int getIdReceta() {
        return idReceta;
    }

    private String getDosis() {
        return dosis;
    }

    private void getIdMedicamento() {
        return idMedicamento;
    }

    public Cita get() {
        return ;
    }

    public Cita get() {
        return ;
    }

    public Medicamento get1() {
        return 1;
    }

    public Set<Medicamento> get() {
        return ;
    }

    private void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }

    private void setDosis(String dosis) {
        this.dosis = dosis;
    }

    private void setIdMedicamento(void idMedicamento) {
        this.idMedicamento = idMedicamento;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set(Cita ) {
        this. = ;
    }

    public void set1(Medicamento 1) {
        this.1 = 1;
    }

    public void link(Cita _) {
        set(_);
    }

    public void link(Cita _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link1(Medicamento _1) {
        if (_1 != null) {
            _1.unlink*();
            _1.set*(this);
        }

        unlink1();
        set1(_1);
    }

    public void link(Medicamento _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink() {
        set(null);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink1() {
        if (get1() != null) {
            get1().set*(null);
            set1(null);
        }
    }

    public void unlink(Medicamento _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Medicamento _, Iterator<Medicamento> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAF83JmZraChYRU= >>
    // ----------- >>
    public void imprimirReceta() {
    // ----------- << method.body@AAAAAAF83JmZraChYRU= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83IwL0J9IV4s= >>
// ----------- >>
}