/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package agenda;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF83HU1uZ6/pwI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF83HU1uZ6/pwI= >>
// ----------- >>
public class Usuario {
    // ----------- << attribute.annotations@AAAAAAF83HVcDJ7pfg8= >>
    // ----------- >>
    private int idUsuario;

    // ----------- << attribute.annotations@AAAAAAF83HWPwJ7wUN4= >>
    // ----------- >>
    private int nombre;

    // ----------- << attribute.annotations@AAAAAAF83HXtyZ73c7c= >>
    // ----------- >>
    private String contraseña;

    // ----------- << attribute.annotations@AAAAAAF83Lbj/rbmKU8= >>
    // ----------- >>
    private Main ;

    private int getIdUsuario() {
        return idUsuario;
    }

    private int getNombre() {
        return nombre;
    }

    private String getContraseña() {
        return contraseña;
    }

    public Main get() {
        return ;
    }

    private void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    private void setNombre(int nombre) {
        this.nombre = nombre;
    }

    private void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

    public void set(Main ) {
        this. = ;
    }

    public void link(Main _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAF83Jk+f6CYimE= >>
    // ----------- >>
    public void altaUsuario() {
    // ----------- << method.body@AAAAAAF83Jk+f6CYimE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83I/dFp/3vk0= >>
    // ----------- >>
    public void bajaUsuario() {
    // ----------- << method.body@AAAAAAF83I/dFp/3vk0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF83Ji/ZKCRF6w= >>
    // ----------- >>
    public void actualizaUsuario() {
    // ----------- << method.body@AAAAAAF83Ji/ZKCRF6w= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF83HU1uZ6/pwI= >>
// ----------- >>
}